### ISSUE TITLE
Random text after converting 

### ISSUE THREAD

**Issue by anandh-kumar** [average-linux-user/Sticky-Notes#2]
I found this text after switching to dark theme.
![image](https://user-images.githubusercontent.com/77324752/183300074-8c1042e6-c3c2-4fd8-af17-3d62d3d68c45.png)

**Comment by average-linux-user** [comment]
For now that's our way to save  dark mode but in a future update we can make our own file extensions or we can keep a file known as `text.conf` to store the config files. We are looking to fix this
