### ISSUE TITLE
pog no more

### ISSUE THREAD

**Issue by tusharhero** [average-linux-user/Sticky-Notes#5]
` curl https://raw.githubusercontent.com/average-linux-user/Sticky-Notes/main/Sticky.py | python`

doesnt work anymore.
I believe b1ae86a1b42a008bad203c77ea2df643f380395e caused the issue.

@Techlord210  what did u do ??

**Comment by tusharhero** [comment]
```
 ╭─tusharhero@tushars in ~ 
 ╰─λ curl https://raw.githubusercontent.com/average-linux-user/Sticky-Notes/main/Sticky.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11172  100 11172    0     0  12275      0 --:--:-- --:--:-- --:--:-- 12276
There are errors loading JSON file. crash log saved to log.txt

```

**Comment by Techlord210** [comment]
> ```
>  ╭─tusharhero@tushars in ~ 
>  ╰─λ curl https://raw.githubusercontent.com/average-linux-user/Sticky-Notes/main/Sticky.py | python
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 11172  100 11172    0     0  12275      0 --:--:-- --:--:-- --:--:-- 12276
> There are errors loading JSON file. crash log saved to log.txt
> ```

delete `.sticky,json` and try again and you can read log.txt for json errors
